config_version: 1

slot_unlocks:
  1: 0
  2: 30
  3: 100

limit_breaking:
  sharpness:
    1: 50
    2: 70
  smite:
    1: 50
    2: 70
  bane_of_arthropods:
    1: 50
    2: 70
  power:
    1: 50
    2: 70
  protection:
    1: 55
    2: 75
  fire_protection:
    1: 55
    2: 75
  projectile_protection:
    1: 55
    2: 75
  sweeping_edge:
    1: 50
    2: 70
  quick_charge:
    1: 45
    2: 60
  unbreaking:
    1: 48
    2: 68
  looting:
    1: 58
    2: 82
  impaling:
    1: 55
    2: 75
  knockback:
    1: 45
    2: 60
    3: 80
  fire_aspect:
    1: 55
    2: 75
    3: 95
  feather_falling:
    1: 48
    2: 68
  blast_protection:
    1: 55
    2: 75

incompatible_combination:
  infinity_mending: 55
  multishot_piercing: 58
  damage_smite: 60
  damage_bane_of_arthropods: 60
  protection_fire_protection: 65
  protection_blast_protection: 65
  protection_projectile_protection: 65

invalid_target_attach:
  infinity: 75
  power: 75
  breach: 80

