# テーマIDごとに向きを定義します。
# theme_id:
#   icon: STONE
#   max_summon_count: 10
#   clear_mob_count: 20
#   mobs: # config/mob_definition.yml の id を指定
#     zombie_basic:
#       weight: 10
#       wave: 1..
#     skeleton_basic:
#       weight: 6
#       wave: 2..5
#   door_open_sound:
#     key: minecraft:block.iron_door.open
#     pitch: 1.0
#   orientation:
#     entrance_exit: north
#     corner_entry: north
#     corner_exit: east
#     straight_entry: north
#     corridor_entry: north
#     goal_entry: north

ruins:
  icon: STONE
  max_summon_count: 10
  clear_mob_count: 20
  door_open_sound:
    key: minecraft:block.iron_door.open
    pitch: 1.0
  mobs:
    zombie_normal:
      weight: 8
      wave: 1..
    zombie_light_leap:
      weight: 9
      wave: 1..
    zombie_heavy_shield:
      weight: 7
      wave: 3..
    zombie_archer:
      weight: 7
      wave: 2..
    zombie_archer_swap:
      weight: 8
      wave: 3..
    skeleton_normal:
      weight: 7
      wave: 1..
    skeleton_plain:
      weight: 7
      wave: 1..
    skeleton_rapid:
      weight: 7
      wave: 2..
    skeleton_curve_backstep:
      weight: 6
      wave: 3..
    skeleton_heavy_bow_shield:
      weight: 6
      wave: 3..
    skeleton_throw_close:
      weight: 7
      wave: 2..
    iron_golem_normal:
      weight: 2
      wave: 4..
    iron_golem_magnet:
      weight: 2
      wave: 5..
  orientation:
    entrance_exit: north
    corner_entry: south
    corner_exit: east
    straight_entry: south
    corridor_entry: south
    goal_entry: west

desert_temple:
  icon: CHISELED_SANDSTONE
  max_summon_count: 10
  clear_mob_count: 20
  door_open_sound:
    key: minecraft:block.iron_door.open
    pitch: 1.0
  mobs:
    husk_normal:
      weight: 8
      wave: 1..
    husk_light_leap:
      weight: 9
      wave: 1..
    husk_heavy_shield:
      weight: 7
      wave: 3..
    husk_archer:
      weight: 7
      wave: 2..
    husk_archer_swap:
      weight: 8
      wave: 3..
    husk_weakening_aura:
      weight: 6
      wave: 3..
    skeleton_normal:
      weight: 8
      wave: 1..
    skeleton_plain:
      weight: 7
      wave: 1..
    skeleton_rapid:
      weight: 7
      wave: 2..
    skeleton_curve_backstep:
      weight: 6
      wave: 3..
    skeleton_heavy_bow_shield:
      weight: 6
      wave: 3..
    skeleton_throw_close:
      weight: 7
      wave: 2..
    silverfish_plain:
      weight: 10
      wave: 2..
    silverfish_big_poison:
      weight: 5
      wave: 4..
    spider_plain:
      weight: 8
      wave: 1..
    spider_stealth:
      weight: 7
      wave: 2..
    spider_swift:
      weight: 7
      wave: 2..
    spider_ferocious:
      weight: 6
      wave: 3..
    spider_venom_frenzy:
      weight: 5
      wave: 4..
    spider_broodmother:
      weight: 3
      wave: 5..
    silverfish_stealth_fang:
      weight: 3
      wave: 4..
  orientation:
    entrance_exit: south
    corner_entry: north
    corner_exit: west
    straight_entry: east
    corridor_entry: north
    goal_entry: east

ocean_monument:
  icon: PRISMARINE_BRICKS
  max_summon_count: 10
  clear_mob_count: 20
  door_open_sound:
    key: minecraft:block.iron_door.open
    pitch: 1.0
  mobs:
    zombie_ocean_normal:
      weight: 8
      wave: 1..
    zombie_ocean_warrior:
      weight: 12
      wave: 2..
    drowned_grudge:
      weight: 2
      wave: 3..
    drowned_power_throw:
      weight: 2
      wave: 2..
    water_spirit:
      weight: 2
      wave: 4..
    guardian_normal:
      weight: 3
      wave: 2..
    guardian_small:
      weight: 2
      wave: 1..
    guardian_drain:
      weight: 2
      wave: 3..
    guardian_beam_burst:
      weight: 1
      wave: 4..
  orientation:
    entrance_exit: north
    corner_entry: south
    corner_exit: east
    straight_entry: south
    corridor_entry: south
    goal_entry: west

natura:
  icon: MOSSY_COBBLESTONE
  max_summon_count: 10
  clear_mob_count: 20
  door_open_sound:
    key: minecraft:block.iron_door.open
    pitch: 1.0
  mobs:
    zombie_normal:
      weight: 8
      wave: 1..
    zombie_light_leap:
      weight: 9
      wave: 1..
    zombie_heavy_shield:
      weight: 7
      wave: 3..
    zombie_archer:
      weight: 7
      wave: 2..
    zombie_archer_swap:
      weight: 8
      wave: 3..
    bogged_plain:
      weight: 7
      wave: 1..
    bogged_normal:
      weight: 8
      wave: 1..
    bogged_rapid:
      weight: 7
      wave: 2..
    bogged_curve_backstep:
      weight: 6
      wave: 3..
    bogged_heavy_bow_shield:
      weight: 6
      wave: 3..
    bogged_throw_close:
      weight: 7
      wave: 2..
    spider_plain:
      weight: 8
      wave: 1..
    spider_stealth:
      weight: 7
      wave: 2..
    spider_swift:
      weight: 7
      wave: 2..
    spider_ferocious:
      weight: 6
      wave: 3..
    spider_venom_frenzy:
      weight: 5
      wave: 4..
    spider_broodmother:
      weight: 3
      wave: 5..
    frog_big:
      weight: 4
      wave: 3..
    slime_merge_small:
      weight: 10
      wave: 1..
    slime_merge_medium:
      weight: 7
      wave: 2..
    slime_merge_large:
      weight: 3
      wave: 4..
    slime_poison:
      weight: 5
      wave: 3..
    slime_wither:
      weight: 4
      wave: 4..
    witch_normal:
      weight: 6
      wave: 2..
    witch_elite:
      weight: 3
      wave: 4..
    bat_venom:
      weight: 2
      wave: 4..
  orientation:
    entrance_exit: north
    corner_entry: south
    corner_exit: east
    straight_entry: south
    corridor_entry: south
    goal_entry: west

nether:
  icon: NETHER_BRICKS
  max_summon_count: 10
  clear_mob_count: 20
  door_open_sound:
    key: minecraft:block.nether_bricks.place
    pitch: 0.9
  mobs:
    blaze_normal:
      weight: 10
      wave: 1..
    blaze_rapid:
      weight: 8
      wave: 2..
    blaze_melee:
      weight: 6
      wave: 3..
    blaze_power:
      weight: 4
      wave: 4..
    blaze_beam:
      weight: 3
      wave: 5..
  orientation:
    entrance_exit: north
    corner_entry: south
    corner_exit: east
    straight_entry: south
    corridor_entry: south
    goal_entry: west
