config_version: 2

# CC-Content Root Config

content_enabled:
  arena: true
  rank: true
  brewery: true
  cooking: true
  fishing: true
  resource_collection: true
  seasonal: true
  sukima_dungeon: true
  party: true
  minigame: true

persistence:
  flush_interval_minutes: 1
