name: CC-Content
version: 1.0.0
main: jp.awabi2048.cccontent.CCContent
api-version: '1.21'
author: awabi2048
description: Paper 1.21.8用統合コンテンツプラグイン

commands:
  cc-content:
    description: CC-Contentメインコマンド
    usage: /cc-content reload
    aliases: [cc, ccc]
  rank:
    description: ランクシステムコマンド（デバッグ用）
    usage: /rank <subcommand> [args]
    permission: cc-content.admin
  sukima_dungeon:
    description: スキマダンジョンコマンド
    usage: /sukima_dungeon
    aliases: [sd]
    permission: sukimadungeon.command.base
  arenaa:
    description: アリーナ管理コマンド
    usage: /arenaa <start|stop|theme>
    permission: cc-content.arena.admin
  rankmenu:
    description: 職業メインメニューを開く
    usage: /rankmenu [skill]
    permission: cc-content.rank

permissions:
  cc-content.rank:
    description: 職業メインメニューを開ける
    default: true
  sukimadungeon.command.base:
    description: Allows using the base command
    default: true
  sukimadungeon.admin:
    description: Admin permissions
    default: op
  cc-content.arena.admin:
    description: アリーナ管理コマンドを実行できる
    default: op
