themes:
  test:
    icon: GRASS_BLOCK
    path: test
    tileSize: 16
    void_y_limit: 10.0
    mobs:
      - id: zombie_basic
        weight: 10
        min_dist: 0
        max_dist: 50
  cave:
    icon: COBBLESTONE
    path: cave
    tileSize: 32
    mobs:
      - id: zombie_basic
        weight: 10
        min_dist: 0
        max_dist: 50
      - id: skeleton_basic
        weight: 8
        min_dist: 0
        max_dist: 60
  mineshaft:
    icon: CHEST_MINECART
    path: mineshaft
    tileSize: 48
    mobs:
      - id: zombie_basic
        weight: 8
        min_dist: 0
        max_dist: 50
      - id: skeleton_basic
        weight: 8
        min_dist: 0
        max_dist: 60
  library:
    icon: BOOKSHELF
    path: library
    tileSize: 48
    mobs:
      - id: skeleton_basic
        weight: 12
        min_dist: 0
        max_dist: 60
  ruin:
    icon: CHISELED_STONE_BRICKS
    path: ruins
    tileSize: 48
    mobs:
      - id: zombie_basic
        weight: 8
        min_dist: 0
        max_dist: 50
      - id: skeleton_basic
        weight: 8
        min_dist: 0
        max_dist: 60
      - id: zombie_boss
        weight: 3
        min_dist: 40
        max_dist: 1000
  see_of_trees:
    icon: MOSS_BLOCK
    path: see_of_trees
    tileSize: 48
    mobs:
      - id: zombie_basic
        weight: 10
        min_dist: 0
        max_dist: 50
  maze:
    icon: COMPASS
    path: maze
    tileSize: 48
    mobs:
      - id: zombie_basic
        weight: 8
        min_dist: 0
        max_dist: 50
      - id: skeleton_basic
        weight: 8
        min_dist: 0
        max_dist: 60
