config_version: 2
garden:
  seed_drop_chance: 0.05
  growth_check_interval_seconds: 1
  seed_source_materials:
    - SHORT_GRASS
    - TALL_GRASS
  plants:
    apple:
      seed_language_key: custom_items.brewery.garden_seed_apple.name
      fruit_language_key: custom_items.brewery.garden_fruit_apple.name
      regrowth_stage: 0
      stages:
        0:
          material: SWEET_BERRY_BUSH
          block_data: '[age=0]'
          growth_seconds: 300
        1:
          material: SWEET_BERRY_BUSH
          block_data: '[age=1]'
          growth_seconds: 300
        2:
          material: SWEET_BERRY_BUSH
          block_data: '[age=3]'
          growth_seconds: 300
    blueberry:
      seed_language_key: custom_items.brewery.garden_seed_blueberry.name
      fruit_language_key: custom_items.brewery.garden_fruit_blueberry.name
      regrowth_stage: 0
      stages:
        0:
          material: SWEET_BERRY_BUSH
          block_data: '[age=0]'
          growth_seconds: 240
        1:
          material: SWEET_BERRY_BUSH
          block_data: '[age=2]'
          growth_seconds: 240
        2:
          material: SWEET_BERRY_BUSH
          block_data: '[age=3]'
          growth_seconds: 240
    grape:
      seed_language_key: custom_items.brewery.garden_seed_grape.name
      fruit_language_key: custom_items.brewery.garden_fruit_grape.name
      regrowth_stage: 0
      stages:
        0:
          material: SWEET_BERRY_BUSH
          block_data: '[age=0]'
          growth_seconds: 360
        1:
          material: SWEET_BERRY_BUSH
          block_data: '[age=2]'
          growth_seconds: 360
        2:
          material: SWEET_BERRY_BUSH
          block_data: '[age=3]'
          growth_seconds: 360
    strawberry:
      seed_language_key: custom_items.brewery.garden_seed_strawberry.name
      fruit_language_key: custom_items.brewery.garden_fruit_strawberry.name
      regrowth_stage: 0
      stages:
        0:
          material: SWEET_BERRY_BUSH
          block_data: '[age=0]'
          growth_seconds: 180
        1:
          material: SWEET_BERRY_BUSH
          block_data: '[age=1]'
          growth_seconds: 180
        2:
          material: SWEET_BERRY_BUSH
          block_data: '[age=3]'
          growth_seconds: 180

