config_version: 6
enabled: true

chisel:
  target_count: 3
  target_timeout_ticks: 50
  particle_count: 5

mineral:
  enabled: true
  normal_bonus_drop: true
  work_speed: true
  inspection: true
  chisel_game: true
  batch_mining: true

forest:
  enabled: true
  normal_bonus_drop: true
  work_speed: true
  batch_felling: true
  heartwood: true
  bark: true
  timber_processing: true
  forest_products: true
  leaf_cleanup: true
  automatic_replant: true

crop:
  enabled: true
  normal_bonus_drop: true
  work_speed: true
  wild_gathering: true
  surface_gathering: true
  area_tilling: true
  area_harvest: true
  automatic_replant: true
