# 大工のスキルツリー定義
skills:
  settings:
    level:
      initialExp: 100
      base: 1.25
      maxLevel: 50
    overviewIcon: "CRAFTING_TABLE"

  initial:
    requiredLevel: 0
    icon: "OAK_PLANKS"
    children: ["skill1"]

  skill1:
    requiredLevel: 5
    icon: "ITEM_FRAME"
    children: ["skill2"]

  skill2:
    requiredLevel: 15
    icon: "STONECUTTER"
    children: ["skill3"]

  skill3:
    requiredLevel: 25
    icon: "ENCHANTED_BOOK"
    effect:
      type: "general.unlock_item_token"
      params:
        items: ["carpenter_hammer_token"]
    children: []
