skills:
  settings:
    level:
      initialExp: 100
      base: 1.25
      maxLevel: 50
    overviewIcon: FISHING_ROD
    bossBarColor: AQUA
  initial:
    requiredLevel: 0
    icon: FISHING_ROD
    children: [patient_cast]
  patient_cast:
    requiredLevel: 5
    icon: LILY_PAD
    children: [deep_water]
  deep_water:
    requiredLevel: 15
    icon: NAUTILUS_SHELL
    children: [master_angler]
  master_angler:
    requiredLevel: 30
    icon: HEART_OF_THE_SEA
    children: []
