# 庭師のスキルツリー定義
skills:
  settings:
    level:
      initialExp: 100
      base: 1.25
      maxLevel: 50
    overviewIcon: "FLOWER_POT"

  initial:
    requiredLevel: 0
    icon: "OAK_SAPLING"
    children: ["skill1"]

  skill1:
    requiredLevel: 5
    icon: "FEATHER"
    children: ["skill2"]

  skill2:
    requiredLevel: 10
    icon: "SHULKER_BOX"
    children: ["skill3"]

  skill3:
    requiredLevel: 15
    icon: "BRUSH"
    children: ["skill4"]

  skill4:
    requiredLevel: 20
    icon: "STICK"
    children: ["skill5"]

  skill5:
    requiredLevel: 25
    icon: "ENCHANTED_BOOK"
    effect:
      type: "general.unlock_item_token"
      params:
        items: ["gardener_shears_token"]
    children: []
