config_version: 4

oage_box:
  rewards:
    item:
      misc.boxed_daiginjo:
        amount: 1
        weight: 4
      misc.storage_box_single:
        amount: 1
        weight: 2
      misc.big_light:
        amount: 1
        weight: 3
      misc.small_light:
        amount: 1
        weight: 3
      misc.invisible_item_frame:
        amount: 2
        weight: 3
      misc.invisible_glow_item_frame:
        amount: 1
        weight: 2
      misc.air_cannon:
        amount: 1
        weight: 1
      misc.auto_ignition_booster:
        amount: 1
        weight: 1
    dg:
      - amount: 10
        weight: 4
      - amount: 30
        weight: 2
      - amount: 50
        weight: 1
    world_point:
      - amount: 5
        weight: 4
      - amount: 10
        weight: 2
      - amount: 20
        weight: 1

